### 로컬환경에서의 개발서버 프로필 ###
# 해당 프로필은 로컬환경에서 개발서버를 구축할떄 사용됩니다.
# 서버는 localhost:8080 에 구축됩니다.
# 그외 DB 정보등의 기타 정보는 필요에 따라 유동적으로 바꾸어사용해주세요.

server:
  address: 127.0.0.1
  port: 8080
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${IAM_ACCESS_KEY}
      secret-key: ${IAM_PRIVATE_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/monolithic_api_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
soom:
  email:
    jwt:
      secret: ${SOOM_EMAIL_JWT_SECRET}
      expired-second: ${SOOM_EMAIL_JWT_EXPIRED_SECOND}
    smtp:
      title: '[SOOM] 인증메일이 도착했어요!'
      template-path: /templates/email/auth-email.html
#로컬환경에서 운영되므로, EC2 Metadata 설정중 오류가 발생한다.
# 자세한 내용은 https://h-kkaemi.tistory.com/24 참조
logging.level.com.amazonaws.util.EC2MetadataUtils: error